import betterproto
from game_server.net.session import Session
from lib.proto import (
    GetAvatarRollDataReq,
    GetAvatarRollDataRsp,
    AvatarRoll
)

async def handle(session: Session, msg: GetAvatarRollDataReq) -> betterproto.Message:
    return GetAvatarRollDataRsp(
        retcode=0,
        is_all=True,
        roll_list=[
            AvatarRoll(
                avatar_id=101,
                is_unlock=True
            ),
            AvatarRoll(
                avatar_id=102,
                is_unlock=True
            ),
            AvatarRoll(
                avatar_id=103,
                is_unlock=True
            ),
            AvatarRoll(
                avatar_id=104,
                is_unlock=True
            ),
            AvatarRoll(
                avatar_id=105,
                is_unlock=True
            ),
            AvatarRoll(
                avatar_id=106,
                is_unlock=True
            ),
            AvatarRoll(
                avatar_id=111,
                is_unlock=True
            ),
            AvatarRoll(
                avatar_id=112,
                is_unlock=True
            ),
            AvatarRoll(
                avatar_id=113,
                is_unlock=True
            ),
            AvatarRoll(
                avatar_id=114,
                is_unlock=True
            ),
            AvatarRoll(
                avatar_id=201,
                is_unlock=True
            ),
            AvatarRoll(
                avatar_id=202,
                is_unlock=True
            ),
            AvatarRoll(
                avatar_id=203,
                is_unlock=True
            ),
            AvatarRoll(
                avatar_id=204,
                is_unlock=True
            ),
            AvatarRoll(
                avatar_id=205,
                is_unlock=True
            ),
            AvatarRoll(
                avatar_id=206,
                is_unlock=True
            ),
            AvatarRoll(
                avatar_id=211,
                is_unlock=True
            ),
            AvatarRoll(
                avatar_id=212,
                is_unlock=True
            ),
            AvatarRoll(
                avatar_id=213,
                is_unlock=True
            ),
            AvatarRoll(
                avatar_id=214,
                is_unlock=True
            ),
            AvatarRoll(
                avatar_id=301,
                is_unlock=True
            ),
            AvatarRoll(
                avatar_id=302,
                is_unlock=True
            ),
            AvatarRoll(
                avatar_id=303,
                is_unlock=True
            ),
            AvatarRoll(
                avatar_id=311,
                is_unlock=True
            ),
            AvatarRoll(
                avatar_id=312,
                is_unlock=True
            ),
            AvatarRoll(
                avatar_id=313,
                is_unlock=True
            ),
            AvatarRoll(
                avatar_id=314,
                is_unlock=True
            ),
            AvatarRoll(
                avatar_id=317,
                is_unlock=True
            ),
            AvatarRoll(
                avatar_id=401,
                is_unlock=True
            ),
            AvatarRoll(
                avatar_id=402,
                is_unlock=True
            ),
            AvatarRoll(
                avatar_id=403,
                is_unlock=True
            ),
            AvatarRoll(
                avatar_id=404,
                is_unlock=True
            ),
            AvatarRoll(
                avatar_id=411,
                is_unlock=True
            ),
            AvatarRoll(
                avatar_id=412,
                is_unlock=True
            ),
            AvatarRoll(
                avatar_id=421,
                is_unlock=True
            ),
            AvatarRoll(
                avatar_id=422,
                is_unlock=True
            ),
            AvatarRoll(
                avatar_id=501,
                is_unlock=True
            ),
            AvatarRoll(
                avatar_id=502,
                is_unlock=True
            ),
            AvatarRoll(
                avatar_id=503,
                is_unlock=True
            ),
            AvatarRoll(
                avatar_id=504,
                is_unlock=True
            ),
            AvatarRoll(
                avatar_id=506,
                is_unlock=True
            ),
            AvatarRoll(
                avatar_id=507,
                is_unlock=True
            ),
            AvatarRoll(
                avatar_id=511,
                is_unlock=True
            ),
            AvatarRoll(
                avatar_id=601,
                is_unlock=True
            ),
            AvatarRoll(
                avatar_id=602,
                is_unlock=True
            ),
            AvatarRoll(
                avatar_id=603,
                is_unlock=True
            ),
            AvatarRoll(
                avatar_id=604,
                is_unlock=True
            ),
            AvatarRoll(
                avatar_id=611,
                is_unlock=True
            ),
            AvatarRoll(
                avatar_id=612,
                is_unlock=True
            ),
            AvatarRoll(
                avatar_id=702,
                is_unlock=True
            ),
            AvatarRoll(
                avatar_id=703,
                is_unlock=True
            ),
            AvatarRoll(
                avatar_id=705,
                is_unlock=True
            ),
            AvatarRoll(
                avatar_id=706,
                is_unlock=True
            ),
            AvatarRoll(
                avatar_id=711,
                is_unlock=True
            ),
            AvatarRoll(
                avatar_id=712,
                is_unlock=True
            ),
            AvatarRoll(
                avatar_id=713,
                is_unlock=True
            ),
            AvatarRoll(
                avatar_id=714,
                is_unlock=True
            ),
            AvatarRoll(
                avatar_id=801,
                is_unlock=True
            ),
            AvatarRoll(
                avatar_id=802,
                is_unlock=True
            ),
            AvatarRoll(
                avatar_id=803,
                is_unlock=True
            ),
            AvatarRoll(
                avatar_id=2201,
                is_unlock=True
            ),
            AvatarRoll(
                avatar_id=2202,
                is_unlock=True
            ),
            AvatarRoll(
                avatar_id=2401,
                is_unlock=True
            ),
            AvatarRoll(
                avatar_id=2501,
                is_unlock=True
            ),
            AvatarRoll(
                avatar_id=2601,
                is_unlock=True
            ),
            AvatarRoll(
                avatar_id=2801,
                is_unlock=True
            ),
            AvatarRoll(
                avatar_id=2901,
                is_unlock=True
            ),
            AvatarRoll(
                avatar_id=2902,
                is_unlock=True
            ),
            AvatarRoll(
                avatar_id=3101,
                is_unlock=True
            ),
            AvatarRoll(
                avatar_id=3201,
                is_unlock=True
            ),
            AvatarRoll(
                avatar_id=3301,
                is_unlock=True
            ),
            AvatarRoll(
                avatar_id=3501,
                is_unlock=True
            ),
            AvatarRoll(
                avatar_id=3601,
                is_unlock=True
            ),
            AvatarRoll(
                avatar_id=3701,
                is_unlock=True
            ),
            AvatarRoll(
                avatar_id=20201,
                is_unlock=True
            ),
            AvatarRoll(
                avatar_id=20301,
                is_unlock=True
            ),
            AvatarRoll(
                avatar_id=20401,
                is_unlock=True
            ),
            AvatarRoll(
                avatar_id=70005,
                progress=18
            ),
            AvatarRoll(
                avatar_id=70006,
                progress=18
            ),
            AvatarRoll(
                avatar_id=70010,
                progress=18
            ),
            AvatarRoll(
                avatar_id=70011,
                has_take_group_list=[
                    111
                ],
                progress=33
            ),
            AvatarRoll(
                avatar_id=70019,
                has_take_group_list=[
                    191,
                    192
                ],
                progress=87
            ),
            AvatarRoll(
                avatar_id=70022,
                has_take_group_list=[
                    221,
                    222
                ],
                is_unlock=True,
                progress=68
            ),
            AvatarRoll(
                avatar_id=70025,
                has_take_group_list=[
                    251,
                    252
                ],
                progress=87
            ),
            AvatarRoll(
                avatar_id=70030,
                has_take_group_list=[
                    301,
                    302
                ],
                progress=87
            ),
            AvatarRoll(
                avatar_id=70032,
                has_take_group_list=[
                    321
                ],
                progress=33
            ),
            AvatarRoll(
                avatar_id=70038,
                progress=21
            ),
            AvatarRoll(
                avatar_id=70065,
                progress=33
            ),
            AvatarRoll(
                avatar_id=70080,
                has_take_group_list=[
                    801,
                    802
                ],
                is_unlock=True,
                progress=63
            )
        ]
    )
