import betterproto
from game_server.net.session import Session
from lib.proto import (
    GetDormDataReq,
    GetDormDataRsp,
    DepotFurniture,
    DormEvent,
    DormHouse,
    DormRoom,
    Furniture
)

async def handle(session: Session, msg: GetDormDataReq) -> betterproto.Message:
    return GetDormDataRsp(
        retcode=0,
        depot_furniture_list=[
            DepotFurniture(
                id=140001,
                num=1
            ),
            DepotFurniture(
                id=140002,
                num=1
            ),
            DepotFurniture(
                id=140003,
                num=1
            ),
            DepotFurniture(
                id=140010,
                num=1
            ),
            DepotFurniture(
                id=140012,
                num=1
            ),
            DepotFurniture(
                id=140013,
                num=1
            ),
            DepotFurniture(
                id=140015,
                num=1
            ),
            DepotFurniture(
                id=140016,
                num=1
            ),
            DepotFurniture(
                id=140201,
                num=1
            ),
            DepotFurniture(
                id=140202,
                num=1
            ),
            DepotFurniture(
                id=140213,
                num=1
            ),
            DepotFurniture(
                id=140215,
                num=1
            ),
            DepotFurniture(
                id=140216,
                num=1
            ),
            DepotFurniture(
                id=140601,
                num=1
            ),
            DepotFurniture(
                id=140603,
                num=1
            ),
            DepotFurniture(
                id=140801,
                num=1
            ),
            DepotFurniture(
                id=140802,
                num=1
            ),
            DepotFurniture(
                id=140806,
                num=1
            ),
            DepotFurniture(
                id=140810,
                num=1
            ),
            DepotFurniture(
                id=140812,
                num=1
            ),
            DepotFurniture(
                id=140813,
                num=1
            ),
            DepotFurniture(
                id=140814,
                num=1
            ),
            DepotFurniture(
                id=140815,
                num=1
            ),
            DepotFurniture(
                id=140816,
                num=1
            ),
            DepotFurniture(
                id=140817,
                num=1
            ),
            DepotFurniture(
                id=140818,
                num=1
            ),
            DepotFurniture(
                id=140819,
                num=1
            ),
            DepotFurniture(
                id=140820,
                num=1
            ),
            DepotFurniture(
                id=140822,
                num=1
            ),
            DepotFurniture(
                id=141501,
                num=1
            ),
            DepotFurniture(
                id=141601,
                num=1
            ),
            DepotFurniture(
                id=141606,
                num=1
            ),
            DepotFurniture(
                id=141615,
                num=1
            ),
            DepotFurniture(
                id=141619,
                num=1
            ),
            DepotFurniture(
                id=141620,
                num=1
            ),
            DepotFurniture(
                id=141621,
                num=1
            ),
            DepotFurniture(
                id=141622,
                num=1
            ),
            DepotFurniture(
                id=141701,
                num=1
            ),
            DepotFurniture(
                id=141702,
                num=1
            ),
            DepotFurniture(
                id=141703,
                num=1
            ),
            DepotFurniture(
                id=141704,
                num=1
            ),
            DepotFurniture(
                id=141709,
                num=1
            ),
            DepotFurniture(
                id=141713,
                num=1
            ),
            DepotFurniture(
                id=141801,
                num=1
            ),
            DepotFurniture(
                id=141802,
                num=1
            ),
            DepotFurniture(
                id=141804,
                num=1
            ),
            DepotFurniture(
                id=141805,
                num=1
            ),
            DepotFurniture(
                id=141807,
                num=1
            ),
            DepotFurniture(
                id=141808,
                num=1
            ),
            DepotFurniture(
                id=141809,
                num=1
            ),
            DepotFurniture(
                id=141810,
                num=1
            ),
            DepotFurniture(
                id=141811,
                num=1
            ),
            DepotFurniture(
                id=141812,
                num=1
            ),
            DepotFurniture(
                id=141814,
                num=1
            ),
            DepotFurniture(
                id=141815,
                num=1
            ),
            DepotFurniture(
                id=146120,
                num=1
            ),
            DepotFurniture(
                id=146620,
                num=1
            )
        ],
        event_list=[
            DormEvent(
                avatar_id=101,
                event_id_list=[
                    10007,
                    10011
                ]
            ),
            DormEvent(
                avatar_id=102,
                event_id_list=[
                    10007,
                    10011
                ]
            ),
            DormEvent(
                avatar_id=103,
                event_id_list=[
                    10007,
                    10011
                ]
            ),
            DormEvent(
                avatar_id=104,
                event_id_list=[
                    10007,
                    10011
                ]
            ),
            DormEvent(
                avatar_id=105,
                event_id_list=[
                    10007,
                    10011
                ]
            ),
            DormEvent(
                avatar_id=106,
                event_id_list=[
                    10007,
                    10011
                ]
            ),
            DormEvent(
                avatar_id=111,
                event_id_list=[
                    10007,
                    10011
                ]
            ),
            DormEvent(
                avatar_id=112,
                event_id_list=[
                    10007,
                    10011
                ]
            ),
            DormEvent(
                avatar_id=113,
                event_id_list=[
                    10007,
                    10011
                ]
            ),
            DormEvent(
                avatar_id=114,
                event_id_list=[
                    10007,
                    10011
                ]
            ),
            DormEvent(
                avatar_id=201,
                event_id_list=[
                    10007,
                    10011
                ]
            ),
            DormEvent(
                avatar_id=202,
                event_id_list=[
                    10007,
                    10011
                ]
            ),
            DormEvent(
                avatar_id=203,
                event_id_list=[
                    10007,
                    10011
                ]
            ),
            DormEvent(
                avatar_id=204,
                event_id_list=[
                    10007,
                    10011
                ]
            ),
            DormEvent(
                avatar_id=205,
                event_id_list=[
                    10007,
                    10011
                ]
            ),
            DormEvent(
                avatar_id=206,
                event_id_list=[
                    10007,
                    10011
                ]
            ),
            DormEvent(
                avatar_id=211,
                event_id_list=[
                    10007,
                    10011
                ]
            ),
            DormEvent(
                avatar_id=212,
                event_id_list=[
                    10007,
                    10011
                ]
            ),
            DormEvent(
                avatar_id=213,
                event_id_list=[
                    10007,
                    10011
                ]
            ),
            DormEvent(
                avatar_id=214,
                event_id_list=[
                    10007,
                    10011
                ]
            ),
            DormEvent(
                avatar_id=301,
                event_id_list=[
                    10007,
                    10011
                ]
            ),
            DormEvent(
                avatar_id=302,
                event_id_list=[
                    10007,
                    10011
                ]
            ),
            DormEvent(
                avatar_id=303,
                event_id_list=[
                    10007,
                    10011
                ]
            ),
            DormEvent(
                avatar_id=311,
                event_id_list=[
                    10007,
                    10011
                ]
            ),
            DormEvent(
                avatar_id=312,
                event_id_list=[
                    10007,
                    10011
                ]
            ),
            DormEvent(
                avatar_id=313,
                event_id_list=[
                    10007,
                    10011
                ]
            ),
            DormEvent(
                avatar_id=314,
                event_id_list=[
                    10007,
                    10011
                ]
            ),
            DormEvent(
                avatar_id=317,
                event_id_list=[
                    10007,
                    10011
                ]
            ),
            DormEvent(
                avatar_id=401,
                event_id_list=[
                    10007,
                    10011
                ]
            ),
            DormEvent(
                avatar_id=402,
                event_id_list=[
                    10007,
                    10011
                ]
            ),
            DormEvent(
                avatar_id=403,
                event_id_list=[
                    10007,
                    10011
                ]
            ),
            DormEvent(
                avatar_id=404,
                event_id_list=[
                    10007,
                    10011
                ]
            ),
            DormEvent(
                avatar_id=411,
                event_id_list=[
                    10007,
                    10011
                ]
            ),
            DormEvent(
                avatar_id=412,
                event_id_list=[
                    10007,
                    10011
                ]
            ),
            DormEvent(
                avatar_id=421,
                event_id_list=[
                    10007,
                    10011
                ]
            ),
            DormEvent(
                avatar_id=422,
                event_id_list=[
                    10007,
                    10011
                ]
            ),
            DormEvent(
                avatar_id=501,
                event_id_list=[
                    10007,
                    10011
                ]
            ),
            DormEvent(
                avatar_id=502,
                event_id_list=[
                    10007,
                    10011
                ]
            ),
            DormEvent(
                avatar_id=503,
                event_id_list=[
                    10007,
                    10011
                ]
            ),
            DormEvent(
                avatar_id=504,
                event_id_list=[
                    10007,
                    10011
                ]
            ),
            DormEvent(
                avatar_id=506,
                event_id_list=[
                    10007,
                    10011
                ]
            ),
            DormEvent(
                avatar_id=507,
                event_id_list=[
                    10007,
                    10011
                ]
            ),
            DormEvent(
                avatar_id=511,
                event_id_list=[
                    10007,
                    10011
                ]
            ),
            DormEvent(
                avatar_id=601,
                event_id_list=[
                    10007,
                    10011
                ]
            ),
            DormEvent(
                avatar_id=602,
                event_id_list=[
                    10007,
                    10011
                ]
            ),
            DormEvent(
                avatar_id=603,
                event_id_list=[
                    10007,
                    10011
                ]
            ),
            DormEvent(
                avatar_id=604,
                event_id_list=[
                    10007,
                    10011
                ]
            ),
            DormEvent(
                avatar_id=611,
                event_id_list=[
                    10007,
                    10011
                ]
            ),
            DormEvent(
                avatar_id=612,
                event_id_list=[
                    10007,
                    10011
                ]
            ),
            DormEvent(
                avatar_id=702,
                event_id_list=[
                    10007,
                    10011
                ]
            ),
            DormEvent(
                avatar_id=703,
                event_id_list=[
                    10007,
                    10011
                ]
            ),
            DormEvent(
                avatar_id=705,
                event_id_list=[
                    10007,
                    10011
                ]
            ),
            DormEvent(
                avatar_id=706,
                event_id_list=[
                    10007,
                    10011
                ]
            ),
            DormEvent(
                avatar_id=711,
                event_id_list=[
                    10007,
                    10011
                ]
            ),
            DormEvent(
                avatar_id=712,
                event_id_list=[
                    10007,
                    10011
                ]
            ),
            DormEvent(
                avatar_id=713,
                event_id_list=[
                    10007,
                    10011
                ]
            ),
            DormEvent(
                avatar_id=714,
                event_id_list=[
                    10007,
                    10011
                ]
            ),
            DormEvent(
                avatar_id=801,
                event_id_list=[
                    10007,
                    10011
                ]
            ),
            DormEvent(
                avatar_id=802,
                event_id_list=[
                    10007,
                    10011
                ]
            ),
            DormEvent(
                avatar_id=803,
                event_id_list=[
                    10007,
                    10011
                ]
            ),
            DormEvent(
                avatar_id=2201,
                event_id_list=[
                    10007,
                    10011
                ]
            ),
            DormEvent(
                avatar_id=2202,
                event_id_list=[
                    10007,
                    10011
                ]
            ),
            DormEvent(
                avatar_id=2401,
                event_id_list=[
                    10007,
                    10011
                ]
            ),
            DormEvent(
                avatar_id=2501,
                event_id_list=[
                    10007,
                    10011
                ]
            ),
            DormEvent(
                avatar_id=2601,
                event_id_list=[
                    10007,
                    10011
                ]
            ),
            DormEvent(
                avatar_id=2801,
                event_id_list=[
                    10007,
                    10011
                ]
            ),
            DormEvent(
                avatar_id=2901,
                event_id_list=[
                    10007,
                    10011
                ]
            ),
            DormEvent(
                avatar_id=2902,
                event_id_list=[
                    10007,
                    10011
                ]
            ),
            DormEvent(
                avatar_id=3101,
                event_id_list=[
                    10007,
                    10011
                ]
            ),
            DormEvent(
                avatar_id=3201,
                event_id_list=[
                    10007,
                    10011
                ]
            ),
            DormEvent(
                avatar_id=3301,
                event_id_list=[
                    10007,
                    10011
                ]
            ),
            DormEvent(
                avatar_id=3501,
                event_id_list=[
                    10007,
                    10011
                ]
            ),
            DormEvent(
                avatar_id=3601,
                event_id_list=[
                    10007,
                    10011
                ]
            ),
            DormEvent(
                avatar_id=3701,
                event_id_list=[
                    10007,
                    10011
                ]
            ),
            DormEvent(
                avatar_id=20201,
                event_id_list=[
                    10007,
                    10011
                ]
            ),
            DormEvent(
                avatar_id=20301,
                event_id_list=[
                    10007,
                    10011
                ]
            ),
            DormEvent(
                avatar_id=20401,
                event_id_list=[
                    10007,
                    10011
                ]
            )
        ],
        house_list=[
            DormHouse(
                id=101,
                level=39,
                name="HitLey",
                room_list=[
                    DormRoom(
                        avatar_list=[
                            412,705,
                            802,
                            2201,
                            2401
                        ],
                        furniture_list=[
                            Furniture(
                                id=140015
                            ),
                            Furniture(
                                id=140013
                            ),
                            Furniture(
                                id=140016
                            ),
                        ],
                        id=1011
                    ),
                    DormRoom(
                        avatar_list=[
                            105,
                            113,
                            205,
                            313,
                            612
                        ],
                        furniture_list=[
                            Furniture(
                                id=140808,
                                pos_x=1,
                                pos_y=22
                            ),
                            Furniture(
                                id=140809,
                                location=3,
                                pos_x=7,
                                pos_y=5
                            ),
                            Furniture(
                                direction=3,
                                id=140803,
                                pos_x=1,
                                pos_y=15
                            ),
                            Furniture(
                                direction=1,
                                id=140811,
                                pos_x=5,
                                pos_y=14
                            ),
                            Furniture(
                                id=141610,
                                pos_x=2,
                                pos_y=8
                            ),
                            Furniture(
                                id=140812,
                                pos_x=4,
                                pos_y=4
                            ),
                            Furniture(
                                id=141806,
                                pos_x=9,
                                pos_y=7
                            ),
                            Furniture(
                                id=141803,
                                pos_x=11,
                                pos_y=12
                            ),
                            Furniture(
                                id=140821,
                                location=2,
                                pos_x=7,
                                pos_y=3
                            ),
                            Furniture(
                                id=140002,
                                pos_x=26,
                                pos_y=2
                            ),
                            Furniture(
                                id=140804,
                                pos_x=24,
                                pos_y=17
                            ),
                            Furniture(
                                id=140805,
                                pos_x=25,
                                pos_y=15
                            ),
                            Furniture(
                                id=140807,
                                pos_x=23,
                                pos_y=5
                            ),
                            Furniture(
                                id=140825
                            ),
                            Furniture(
                                id=140824
                            ),
                            Furniture(
                                id=140823
                            )
                        ],
                        id=1012
                    ),
                    DormRoom(
                        furniture_list=[
                            Furniture(
                                id=140015
                            ),
                            Furniture(
                                id=140013
                            ),
                            Furniture(
                                id=140016
                            ),
                        ],
                        id=1013
                    )
                ]
            )
        ],
        is_allow_visit=True,
        show_house=101,
        show_room=1012,
        visit_avatar=101
    )
