import betterproto
from game_server.net.session import Session
from lib.proto import (
    GetRewardLineActivityReq,
    GetRewardLineActivityRsp,
    RewardLineActivity
)

async def handle(session: Session, msg: GetRewardLineActivityReq) -> betterproto.Message:
    return GetRewardLineActivityRsp(
        retcode=0,
        reward_line_activity_list=[
            RewardLineActivity(
                id=10
            ),
            RewardLineActivity(
                id=11
            ),
            RewardLineActivity(
                id=12
            ),
            RewardLineActivity(
                id=13
            ),
            RewardLineActivity(
                id=14
            ),
            RewardLineActivity(
                id=15
            ),
            RewardLineActivity(
                id=16
            ),
            RewardLineActivity(
                id=23
            ),
            RewardLineActivity(
                id=24
            ),
            RewardLineActivity(
                id=25
            ),
            RewardLineActivity(
                id=26
            ),
            RewardLineActivity(
                id=27
            ),
            RewardLineActivity(
                id=28
            ),
            RewardLineActivity(
                id=29
            ),
            RewardLineActivity(
                id=30
            ),
            RewardLineActivity(
                id=31
            ),
            RewardLineActivity(
                id=32
            ),
            RewardLineActivity(
                id=33
            ),
            RewardLineActivity(
                id=34
            ),
            RewardLineActivity(
                id=35
            ),
            RewardLineActivity(
                id=36
            ),
            RewardLineActivity(
                id=37
            ),
            RewardLineActivity(
                id=38
            ),
            RewardLineActivity(
                id=39
            ),
            RewardLineActivity(
                id=45
            ),
            RewardLineActivity(
                id=46
            ),
            RewardLineActivity(
                id=47
            ),
            RewardLineActivity(
                id=48
            ),
            RewardLineActivity(
                id=49
            ),
            RewardLineActivity(
                id=50
            ),
            RewardLineActivity(
                id=51
            ),
            RewardLineActivity(
                id=52
            ),
            RewardLineActivity(
                id=53
            ),
            RewardLineActivity(
                id=54
            ),
            RewardLineActivity(
                id=55
            ),
            RewardLineActivity(
                id=56
            ),
            RewardLineActivity(
                id=57
            ),
            RewardLineActivity(
                id=58
            ),
            RewardLineActivity(
                id=59
            ),
            RewardLineActivity(
                id=60
            ),
            RewardLineActivity(
                id=61
            ),
            RewardLineActivity(
                id=62
            ),
            RewardLineActivity(
                id=64
            ),
            RewardLineActivity(
                id=65
            ),
            RewardLineActivity(
                id=66
            ),
            RewardLineActivity(
                id=67
            ),
            RewardLineActivity(
                id=68
            ),
            RewardLineActivity(
                id=69
            ),
            RewardLineActivity(
                id=70
            ),
            RewardLineActivity(
                id=71
            ),
            RewardLineActivity(
                id=72
            )
        ]
    )
        
