import betterproto
from game_server.net.session import Session
from lib.proto import (
    GetVipRewardDataReq,
    GetVipRewardDataRsp,
    VipReward
)

async def handle(session: Session, msg: GetVipRewardDataReq) -> betterproto.Message:
    return GetVipRewardDataRsp(
        retcode=0,
        total_pay_hcoin=17185,
        vip_reward_list=[
            VipReward(
                is_special_shine_list=[
                    1
                ],
                pay_hcoin=10,
                reward_batch=1,
                reward_id_list=[
                    2101,
                    2201
                ],
                special_reward_id_list=[
                    2101
                ],
                taken_reward_id_list=[
                    2101,
                    2201,
                    2251
                ],
                vip_level=1
            ),
            VipReward(
                is_special_shine_list=[
                    1,
                    1
                ],
                pay_hcoin=300,
                reward_batch=1,
                reward_id_list=[
                    2002,
                    2102,
                    2302
                ],
                special_reward_id_list=[
                    2102,
                    2302
                ],
                taken_reward_id_list=[
                    2002,
                    2102,
                    2252,
                    2302
                ],
                vip_level=2
            ),
            VipReward(
                is_special_shine_list=[
                    1,
                    1
                ],
                pay_hcoin=500,
                reward_batch=1,
                reward_id_list=[
                    2103,
                    2203,
                    2303
                ],
                special_reward_id_list=[
                    2103,
                    2303
                ],
                taken_reward_id_list=[
                    2103,
                    2203,
                    2253,
                    2303
                ],
                vip_level=3
            ),
            VipReward(
                is_special_shine_list=[
                    1,
                    1
                ],
                pay_hcoin=1000,
                reward_batch=1,
                reward_id_list=[
                    2004,
                    2104,
                    2304
                ],
                special_reward_id_list=[
                    2104,
                    2304
                ],
                taken_reward_id_list=[
                    2004,
                    2104,
                    2254,
                    2304
                ],
                vip_level=4
            ),
            VipReward(
                is_special_shine_list=[
                    1,
                    1
                ],
                pay_hcoin=2000,
                reward_batch=1,
                reward_id_list=[
                    2105,
                    2205,
                    2305
                ],
                special_reward_id_list=[
                    2105,
                    2305
                ],
                taken_reward_id_list=[
                    2105,
                    2205,
                    2255,
                    2305
                ],
                vip_level=5
            ),
            VipReward(
                is_special_shine_list=[
                    1,
                    1
                ],
                pay_hcoin=5000,
                reward_batch=1,
                reward_id_list=[
                    2006,
                    2106,
                    2306
                ],
                special_reward_id_list=[
                    2106,
                    2306
                ],
                taken_reward_id_list=[
                    2006,
                    2106,
                    2256,
                    2306
                ],
                vip_level=6
            ),
            VipReward(
                is_special_shine_list=[
                    1,
                    1
                ],
                pay_hcoin=10000,
                reward_batch=1,
                reward_id_list=[
                    2107,
                    2207,
                    2257,
                    2307
                ],
                special_reward_id_list=[
                    2107,
                    2307
                ],
                taken_reward_id_list=[
                    2107,
                    2207,
                    2257,
                    2307
                ],
                vip_level=7
            ),
            VipReward(
                is_special_shine_list=[
                    1,
                    1
                ],
                pay_hcoin=20000,
                reward_batch=1,
                reward_id_list=[
                    2108,
                    2208,
                    2258,
                    2308
                ],
                special_reward_id_list=[
                    2108,
                    2308
                ],
                vip_level=8
            ),
            VipReward(
                is_special_shine_list=[
                    1,
                    1
                ],
                pay_hcoin=50000,
                reward_batch=1,
                reward_id_list=[
                    2109,
                    2209,
                    2309
                ],
                special_reward_id_list=[
                    2109,
                    2309
                ],
                vip_level=9
            ),
            VipReward(
                is_special_shine_list=[
                    1,
                    1,
                    1
                ],
                pay_hcoin=100000,
                reward_batch=1,
                reward_id_list=[
                    2110,
                    2210,
                    2310
                ],
                special_reward_id_list=[
                    2110,
                    2310
                ],
                vip_level=10
            ),
            VipReward(
                is_special_shine_list=[
                    1,
                    1,
                    1
                ],
                pay_hcoin=150000,
                reward_batch=1,
                reward_id_list=[
                    2261,
                    2311
                ],
                special_reward_id_list=[
                    2311
                ],
                vip_level=11
            ),
            VipReward(
                is_special_shine_list=[
                    1,
                    1,
                    1
                ],
                pay_hcoin=200000,
                reward_batch=1,
                reward_id_list=[
                    2262,
                    2312
                ],
                special_reward_id_list=[
                    2312
                ],
                vip_level=12
            ),
            VipReward(
                is_special_shine_list=[
                    1
                ],
                pay_hcoin=250000,
                reward_batch=1,
                reward_id_list=[
                    2263,
                    2313
                ],
                special_reward_id_list=[
                    2313
                ],
                vip_level=13
            )
        ]
    )
